name: Robustness
on: [push, pull_request]
permissions: read-all
jobs:
  main:
    uses: ./.github/workflows/robustness-template.yaml
    with:
      etcdBranch: main
      count: 15
      testTimeout: 30m
      artifactName: main
  main-arm64:
    uses: ./.github/workflows/robustness-template.yaml
    with:
      etcdBranch: main
      count: 15
      testTimeout: 30m
      artifactName: main-arm64
      runs-on: "['self-hosted', 'Linux', 'ARM64']"