name: Reusable Robustness Workflow
on:
  workflow_call:
    inputs:
      etcdBranch:
        required: true
        type: string
      count:
        required: true
        type: number
      testTimeout:
        required: false
        type: string
        default: '30m'
      artifactName:
        required: true
        type: string
permissions: read-all
jobs:
  test:
    timeout-minutes: 210
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
    - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      with:
        go-version: '1.19.7'
    - name: build
      env:
        ETCD_BRANCH: "${{ inputs.etcdBranch }}"
      run: |
        set -euo pipefail

        mkdir -p bin
        case "${ETCD_BRANCH}" in
          release-3.5)
            make /tmp/etcd-release-3.5-failpoints/bin/etcd
            cp /tmp/etcd-release-3.5-failpoints/bin/etcd bin/etcd
            ;;
          release-3.4)
            make /tmp/etcd-release-3.4-failpoints/bin/etcd
            cp /tmp/etcd-release-3.4-failpoints/bin/etcd bin/etcd
            ;;
          main)
            make gofail-enable
            make build
            ;;
          *)
            echo "Failed to find target ${ETCD_BRANCH}"
            exit 1
            ;;
        esac
        ./bin/etcd --version
    - name: test-robustness
      run: |
        set -euo pipefail

        # Use --failfast to avoid overriding report generated by failed test
        EXPECT_DEBUG=true GO_TEST_FLAGS='-v --count ${{ inputs.count }} --timeout ${{ inputs.testTimeout }} --failfast --run TestRobustness' RESULTS_DIR=/tmp/results make test-robustness
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ${{ inputs.artifactName }}
        path: /tmp/results/*
